#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#gatt_multi_connect

PROJECT_NAME := client_v2.0

COMPONENT_ADD_INCLUDEDIRS := components/include

include $(IDF_PATH)/make/project.mk
